---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/tektrend/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp dashboard.html $DEPLOYPATH
    - /bin/cp live_demo.html $DEPLOYPATH
    - /bin/cp -R live_demo $DEPLOYPATH
